version: "3.9"

services:
  jupyterhub:
    build: .
    container_name: jupyterhub-gpu
    ports:
      - "8012:8000"
    volumes:
      - jupyterhub_data:/srv/jupyterhub         # 💾 Datos internos del hub
      - ./home:/home                            # 🔗 Usuarios con notebooks montados desde host
      - datausers_jupyterhub:/var/lib/datausers_jupyterhub  # 🆕 Externaliza ~/data
    restart: always
    environment:
      - TZ=America/Guayaquil
    runtime: nvidia  # Asegura que el contenedor use NVIDIA Runtime

# Volúmenes
volumes:
  jupyterhub_data:
  datausers_jupyterhub:                         # 🆕 Volumen externo montado manualmente
    driver: local
    driver_opts:
      type: none
      device: /var/lib/datausers_jupyterhub
      o: bind
